name: fpfn_env
dependencies:
- python=3.10.8
- pip
- pip:
  - numpy==2.1.1
  - fastapi[all]==0.115.0
  - streamlit==1.39.0
  - streamlit-aggrid==1.0.5
  - matplotlib==3.9.2
  - plotly==5.24.1
  - scikit-image==0.24.0
  - pandas==2.2.3